[package]
name = "bit_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
log = "0.4"
pixels = "0.11.0"
simple_logger = "4.0.0"
winit = "0.27"
winit_input_helper = "0.13"
